.PHONY: test build bench profile evaluate quality

test:
	CGO_ENABLED=0 go test ./...
	go test -race ./...

build:
	CGO_ENABLED=0 go build ./...

bench:
	CGO_ENABLED=0 go test -run '^$$' -bench . -benchmem ./...

profile:
	CGO_ENABLED=0 go test -run '^$$' -bench BenchmarkAnalyze1KB -benchtime=3s -cpuprofile=/tmp/languages-cpu.pprof -memprofile=/tmp/languages-mem.pprof -o /tmp/languages-profile.test .

evaluate:
	go run ./cmd/evaluate -corpus testdata/corpus

quality:
	golangci-lint run --enable gocritic,gocognit,gocyclo,maintidx,dupl,mnd,unparam,ireturn,goconst,errcheck ./...
	govulncheck ./...
	deadcode ./...
