package languages

type rule struct {
	id, description          string
	languages                Set
	weight                   uint8
	prefix, contains, suffix string
}

// Each rule contributes once. declaredWeight is reserved for interpreter rules.
var rules = [...]rule{
	{"ruby.shebang", "shebang indicates Ruby", 1 << Ruby, declaredWeight, "@ruby", "", ""},
	{"python.shebang", "shebang indicates Python", 1 << Python, declaredWeight, "@python", "", ""},
	{"shell.shebang", "shebang indicates sh", 1 << Shell, declaredWeight, "@sh", "", ""},
	{"bash.shebang", "shebang indicates Bash", 1 << Bash, declaredWeight, "@bash", "", ""},
	{"zsh.shebang", "shebang indicates Zsh", 1 << Zsh, declaredWeight, "@zsh", "", ""},
	{"fish.shebang", "shebang indicates Fish", 1 << Fish, declaredWeight, "@fish", "", ""},
	{"perl.shebang", "shebang indicates Perl", 1 << Perl, declaredWeight, "@perl", "", ""},
	{"raku.shebang", "shebang indicates Raku", 1 << Raku, declaredWeight, "@raku", "", ""},
	{"node.shebang", "shebang indicates Node.js", 1 << JavaScript, declaredWeight, "@node", "", ""},
	{"php.shebang", "shebang indicates PHP", 1 << PHP, declaredWeight, "@php", "", ""},
	{"lua.shebang", "shebang indicates Lua", 1 << Lua, declaredWeight, "@lua", "", ""},
	{"racket.shebang", "shebang indicates Racket", 1 << Racket, declaredWeight, "@racket", "", ""},
	{"ruby.frozen", "Ruby frozen_string_literal pragma", 1 << Ruby, 7, "#", "frozen_string_literal:", ""},
	{"ruby.require", "Ruby-style require statement", 1 << Ruby, 5, "require ", "", ""},
	{"ruby.require-relative", "Ruby require_relative statement", 1 << Ruby, 6, "require_relative ", "", ""},
	{"ruby.module", "Ruby-style module declaration", 1 << Ruby, 3, "module ", "", ""},
	{"ruby.def", "Ruby-style method declaration", 1 << Ruby, 4, "def ", "", ""},
	{"ruby.end", "end terminator", 1<<Ruby | 1<<Lua | 1<<MATLAB, 1, "end", "", "end"},
	{"ruby.attr", "Ruby attribute declaration", 1 << Ruby, 6, "attr_", ":", ""},
	{"python.def", "Python function declaration", 1 << Python, 6, "def ", "(", ":"},
	{"python.async-def", "Python async function declaration", 1 << Python, 6, "async def ", "(", ":"},
	{"python.from", "Python from/import statement", 1 << Python, 5, "from ", " import ", ""},
	{"python.import", "Python-style import statement", 1 << Python, 3, "import ", "", ""},
	{"python.class", "Python class declaration", 1 << Python, 5, "class ", "", ":"},
	{"python.main", "Python __name__ guard", 1 << Python, 6, "if __name__", "==", ":"},
	{"go.package", "package declaration without semicolon", 1<<Go | 1<<Java, 3, "package ", "", ""},
	{"go.func", "Go function declaration", 1 << Go, 6, "func ", "(", ""},
	{"go.import", "Go import block", 1 << Go, 6, "import (", "", ""},
	{"go.type", "Go struct type declaration", 1 << Go, 6, "type ", " struct", ""},
	{"rust.use", "Rust/Perl/Raku use path", 1<<Rust | 1<<Perl | 1<<Raku, 5, "use ", "::", ";"},
	{"rust.fn", "Rust function declaration", 1 << Rust, 6, "fn ", "(", ""},
	{"rust.pub-fn", "Rust public function declaration", 1 << Rust, 6, "pub fn ", "(", ""},
	{"rust.impl", "Rust impl block", 1 << Rust, 5, "impl ", "{", ""},
	{"rust.derive", "Rust derive attribute", 1 << Rust, 6, "#[derive(", "", ""},
	{"java.package", "Java package declaration", 1 << Java, 5, "package ", "", ";"},
	{"java.import", "Java import path", 1 << Java, 5, "import ", ".", ";"},
	{"java.class", "public class declaration", 1<<Java | 1<<CSharp, 4, "public class ", "", ""},
	{"java.main", "Java main method signature", 1 << Java, 7, "public static void main(", "String", ""},
	{"c.include", "C-family include directive", cFamily, 5, "#include", "", ""},
	{"c.guard", "C-family conditional preprocessor directive", cFamily, 3, "#ifndef ", "", ""},
	{"c.typedef", "C-family typedef", cFamily, 4, "typedef ", "", ""},
	{"c.main", "C-family main function", cFamily, 4, "int main(", "", ""},
	{"cpp.namespace", "C++ namespace block", 1 << CPP, 6, "namespace ", "{", ""},
	{"cpp.using", "C++ using namespace directive", 1 << CPP, 6, "using namespace ", "", ";"},
	{"cpp.template", "C++ template declaration", 1 << CPP, 7, "template", "<", ""},
	{"objc.import", "Objective-C import directive", 1 << ObjectiveC, 6, "#import ", "", ""},
	{"objc.interface", "Objective-C interface declaration", 1 << ObjectiveC, 7, "@interface ", "", ""},
	{"objc.implementation", "Objective-C implementation declaration", 1 << ObjectiveC, 7, "@implementation ", "", ""},
	{"matlab.function", "MATLAB function with output assignment", 1 << MATLAB, 6, "function ", "=", ""},
	{"matlab.class", "MATLAB classdef declaration", 1 << MATLAB, 6, "classdef ", "", ""},
	{"js.function", "JavaScript-family function declaration", jsFamily, 5, "function ", "(", ""},
	{"js.const", "JavaScript-family const declaration", jsFamily, 3, "const ", "=", ""},
	{"js.import", "JavaScript-family import/from statement", jsFamily, 5, "import ", " from ", ""},
	{"js.export", "JavaScript-family default export", jsFamily, 5, "export default ", "", ""},
	{"js.module", "CommonJS module export", jsFamily, 6, "module.exports", "=", ""},
	{"ts.interface", "TypeScript interface declaration", tsFamily, 6, "interface ", "{", ""},
	{"ts.export-interface", "TypeScript exported interface", tsFamily, 6, "export interface ", "{", ""},
	{"ts.type", "TypeScript exported type alias", tsFamily, 6, "export type ", "=", ""},
	{"jsx.return", "JSX-style markup in return expression", jsxFamily, 6, "return ", "<", ">;"},
	{"shell.if", "shell if/then construct", shellFamily, 5, "if ", "; then", ""},
	{"shell.case", "shell case/in construct", shellFamily, 5, "case ", "", " in"},
	{"shell.export", "shell export assignment", shellFamily, 3, "export ", "=", ""},
	{"shell.fi", "shell fi terminator", shellFamily, 3, "fi", "", "fi"},
	{"shell.extended-test", "Bash/Zsh extended test", 1<<Bash | 1<<Zsh, 5, "[[ ", " ]]", ""},
	{"fish.set", "Shell/Fish set command", shellFamily | 1<<Fish, 5, "set -", "", ""},
	{"perl.strict", "Perl strict pragma", 1 << Perl, 6, "use strict", "", ";"},
	{"perl.warnings", "Perl warnings pragma", 1 << Perl, 6, "use warnings", "", ";"},
	{"perl.sub", "Perl/Raku subroutine declaration", 1<<Perl | 1<<Raku, 4, "sub ", "{", ""},
	{"raku.version", "Raku language directive", 1 << Raku, 9, "use v6", "", ";"},
	{"raku.unit", "Raku unit module declaration", 1 << Raku, 7, "unit module ", "", ";"},
	{"lisp.defun", "Common Lisp defun form", 1 << CommonLisp, 6, "(defun ", "", ""},
	{"lisp.package", "Common Lisp package form", 1 << CommonLisp, 6, "(in-package ", "", ""},
	{"scheme.define", "Scheme-family define form", schemeFamily, 5, "(define ", "", ""},
	{"racket.lang", "Racket #lang directive", 1 << Racket, 9, "#lang ", "", ""},
	{"clojure.ns", "Clojure namespace form", 1 << Clojure, 6, "(ns ", "", ""},
	{"clojure.defn", "Clojure defn form", 1 << Clojure, 6, "(defn ", "", ""},
	{"php.open", "PHP opening tag", 1 << PHP, 9, "<?php", "", ""},
	{"lua.local-function", "Lua local function declaration", 1 << Lua, 6, "local function ", "(", ""},
	{"lua.require", "Lua local require assignment", 1 << Lua, 5, "local ", "require", ""},
	{"csharp.using", "C# using directive", 1 << CSharp, 5, "using ", ".", ";"},
	{"csharp.namespace", "C# file-scoped namespace", 1 << CSharp, 6, "namespace ", "", ";"},
	{"csharp.system", "C# System using directive", 1 << CSharp, 6, "using System;", "", ""},
	{"html.doctype", "HTML doctype declaration", 1 << HTML, 9, "<!DOCTYPE html", "", ""},
	{"html.root", "HTML root tag", 1 << HTML, 6, "<html", "", ""},
	{"xml.declaration", "XML declaration", 1 << XML, 9, "<?xml ", "", ""},
	{"template.block", "Jinja/Twig block directive", templateFamily, 5, "{%", "block ", "%}"},
	{"template.extends", "Jinja/Twig extends directive", templateFamily, 6, "{%", "extends ", "%}"},
	{"erb.tag", "ERB-style expression tag", 1 << ERB, 3, "<%=", "", ""},
	{"erb.ruby", "Ruby syntax inside template tag", 1 << ERB, 6, "<%", " do ", ""},
	{"sql.select", "SQL SELECT/FROM statement", 1 << SQL, 5, "SELECT ", " FROM ", ""},
	{"sql.create", "SQL CREATE TABLE statement", 1 << SQL, 6, "CREATE TABLE ", "", ""},
	{"prolog.module", "Prolog module directive", 1 << Prolog, 7, ":- module(", "", ""},
	{"prolog.import", "Prolog use_module directive", 1 << Prolog, 7, ":- use_module(", "", ""},
	{"prolog.rule", "Prolog-style rule clause", 1 << Prolog, 5, "~prolog", "", ""},
	{"prolog.shebang", "shebang indicates SWI-Prolog", 1 << Prolog, declaredWeight, "@swipl", "", ""},
	{"prolog.dynamic", "Prolog dynamic directive", 1 << Prolog, 6, ":- dynamic ", "", "."},
	{"ts.binding", "TypeScript-style binding annotation", tsFamily, 6, "~typed", "", ""},
}
