package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

type stringList []string

func (list *stringList) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind == yaml.ScalarNode {
		*list = []string{node.Value}
		return nil
	}
	var values []string
	if err := node.Decode(&values); err != nil {
		return err
	}
	*list = values
	return nil
}

type heuristicSpec struct {
	Language stringList      `yaml:"language"`
	Pattern  stringList      `yaml:"pattern"`
	Negative stringList      `yaml:"negative_pattern"`
	Named    string          `yaml:"named_pattern"`
	And      []heuristicSpec `yaml:"and"`
}

type heuristicDocument struct {
	Groups []struct {
		Extensions []string        `yaml:"extensions"`
		Rules      []heuristicSpec `yaml:"rules"`
	} `yaml:"disambiguations"`
	Named map[string]stringList `yaml:"named_patterns"`
}

type compiledCondition struct {
	pattern  string
	negative bool
}

var rubyFlags = regexp.MustCompile(`\(\?([im-]+)([:)])`)

func compilePattern(patterns []string) (string, error) {
	var converted []string
	for _, pattern := range patterns {
		pattern = rubyFlags.ReplaceAllStringFunc(pattern, func(flags string) string {
			return strings.ReplaceAll(flags, "m", "s")
		})
		converted = append(converted, "(?:"+pattern+")")
	}
	pattern := "(?m)" + strings.Join(converted, "|")
	if _, err := regexp.Compile(pattern); err != nil {
		return "", err
	}
	return pattern, nil
}

func compileConditions(spec heuristicSpec, named map[string]stringList) ([]compiledCondition, error) {
	if spec.And != nil {
		var result []compiledCondition
		for _, child := range spec.And {
			conditions, err := compileConditions(child, named)
			if err != nil {
				return nil, err
			}
			result = append(result, conditions...)
		}
		return result, nil
	}
	patterns, negative := spec.Pattern, false
	if patterns == nil && spec.Negative != nil {
		patterns, negative = spec.Negative, true
	}
	if patterns == nil && spec.Named != "" {
		var ok bool
		patterns, ok = named[spec.Named]
		if !ok {
			return nil, fmt.Errorf("unknown named pattern %q", spec.Named)
		}
	}
	if patterns == nil {
		return nil, nil
	}
	pattern, err := compilePattern(patterns)
	return []compiledCondition{{pattern, negative}}, err
}

func runHeuristics(source, revisionFile, output string) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	revision, err := os.ReadFile(revisionFile)
	if err != nil {
		return err
	}
	languages, err := os.ReadFile("languages.yml")
	if err != nil {
		return err
	}
	var entries map[string]metadata
	if err := yaml.Unmarshal(languages, &entries); err != nil {
		return err
	}
	_, ids, _ := catalog(entries)
	generated, err := generateHeuristics(data, strings.TrimSpace(string(revision)), ids)
	if err != nil {
		return err
	}
	return os.WriteFile(output, generated, metadataMode)
}

func generateHeuristics(data []byte, revision string, ids map[string]int) ([]byte, error) {
	if decoded, err := hex.DecodeString(revision); err != nil || len(decoded) != 20 {
		return nil, fmt.Errorf("invalid Linguist commit SHA: %q", revision)
	}
	var doc heuristicDocument
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	if len(doc.Groups) == 0 {
		return nil, fmt.Errorf("empty Linguist heuristics")
	}
	patterns := make(map[string]int)
	var patternList []string
	var groups bytes.Buffer
	fmt.Fprintln(&groups, "var heuristicGroups = [...]heuristicGroup{")
	for _, group := range doc.Groups {
		if len(group.Extensions) == 0 || len(group.Rules) == 0 {
			return nil, fmt.Errorf("empty heuristic group")
		}
		fmt.Fprintf(&groups, "{extensions: %#v, rules: []heuristicRule{\n", group.Extensions)
		for _, rule := range group.Rules {
			var languages []int
			for _, name := range rule.Language {
				id, ok := ids[name]
				if !ok || id == 0 {
					return nil, fmt.Errorf("unknown heuristic language %q", name)
				}
				languages = append(languages, id)
			}
			if len(languages) == 0 {
				return nil, fmt.Errorf("missing heuristic language")
			}
			conditions, err := compileConditions(rule, doc.Named)
			if err != nil {
				return nil, fmt.Errorf("%v: %w", group.Extensions, err)
			}
			fmt.Fprintf(&groups, "{languages: %s, conditions: []heuristicCondition{", setLiteral(languages))
			for _, condition := range conditions {
				index, ok := patterns[condition.pattern]
				if !ok {
					index = len(patternList)
					patterns[condition.pattern] = index
					patternList = append(patternList, condition.pattern)
				}
				fmt.Fprintf(&groups, "{%d, %t},", index, condition.negative)
			}
			fmt.Fprintln(&groups, "}},")
		}
		fmt.Fprintln(&groups, "}},")
	}
	fmt.Fprintln(&groups, "}")
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by tools/registrygen; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Linguist heuristics: %s.\n", revision)
	fmt.Fprintln(&out, "// Copyright (c) 2017 GitHub, Inc. MIT license: LICENSE.linguist.")
	fmt.Fprintln(&out, "package languages")
	fmt.Fprintln(&out, "var heuristicPatterns = [...]string{")
	for _, pattern := range patternList {
		fmt.Fprintf(&out, "%q,\n", pattern)
	}
	fmt.Fprintln(&out, "}")
	out.Write(groups.Bytes())
	return format.Source(out.Bytes())
}
