package main

import (
	"bytes"
	"encoding/hex"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type metadata struct {
	Scope          string   `yaml:"tm_scope"`
	FilesystemName string   `yaml:"fs_name"`
	Aliases        []string `yaml:"aliases"`
	Extensions     []string `yaml:"extensions"`
	Filenames      []string `yaml:"filenames"`
	Interpreters   []string `yaml:"interpreters"`
}

const (
	metadataMode = 0644
	wordBits     = 64
	jinjaName    = "Jinja"
)

var existing = []string{"", "Python", "Ruby", "Go", "Rust", "Java", "C", "C++", "Objective-C", "MATLAB", "JavaScript", "TypeScript", "JSX", "TSX", "Shell", "Bash", "Zsh", "Fish", "Perl", "Raku", "Common Lisp", "Scheme", "Clojure", "Racket", "PHP", "Lua", "C#", "HTML", "XML", jinjaName, "Twig", "ERB", "SQL", "Prolog"}
var equivalents = map[string]string{"fish": "Fish", "Jinja2": jinjaName, "HTML+Jinja": jinjaName, "HTML+ERB": "ERB", "HTML+PHP": "PHP", "Matlab": "MATLAB"}

func main() {
	source := flag.String("source", "languages.yml", "Linguist language metadata")
	revision := flag.String("revision-file", "revision", "file containing the Linguist commit SHA")
	output := flag.String("out", "../../registry_generated.go", "generated Go file")
	heuristics := flag.Bool("heuristics", false, "generate extension heuristics")
	flag.Parse()
	if *heuristics {
		if err := runHeuristics(*source, *revision, *output); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}
	if err := run(*source, *revision, *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(source, revisionFile, output string) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	revision, err := os.ReadFile(revisionFile)
	if err != nil {
		return err
	}
	generated, err := generate(data, strings.TrimSpace(string(revision)))
	if err != nil {
		return err
	}
	return os.WriteFile(output, generated, metadataMode)
}

func generate(data []byte, revision string) ([]byte, error) {
	if decoded, err := hex.DecodeString(revision); err != nil || len(decoded) != 20 {
		return nil, fmt.Errorf("invalid Linguist commit SHA: %q", revision)
	}
	var entries map[string]metadata
	if err := yaml.Unmarshal(data, &entries); err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("empty Linguist metadata")
	}
	names, ids, keys := catalog(entries)
	symbols, err := identifiers(names)
	if err != nil {
		return nil, err
	}
	aliases := make(map[string]int)
	for alias, id := range ids {
		if alias != "" {
			aliases[strings.ToLower(alias)] = id
		}
	}
	extensions, filenames, interpreters := make(map[string][]int), make(map[string][]int), make(map[string][]int)
	var xmlLanguages []int
	for _, name := range keys {
		id, meta := ids[name], entries[name]
		if meta.Scope == "text.xml" || strings.HasPrefix(meta.Scope, "text.xml.") {
			xmlLanguages = append(xmlLanguages, id)
		}
		if meta.FilesystemName != "" {
			aliases[strings.ToLower(meta.FilesystemName)] = id
		}
		for _, alias := range append(meta.Aliases, strings.Join(strings.Fields(name), "-")) {
			alias = strings.ToLower(alias)
			if _, exists := aliases[alias]; !exists {
				aliases[alias] = id
			}
		}
		for _, ext := range meta.Extensions {
			ext = strings.ToLower(ext)
			extensions[ext] = append(extensions[ext], id)
		}
		for _, filename := range meta.Filenames {
			filenames[filename] = append(filenames[filename], id)
		}
		for _, executable := range meta.Interpreters {
			interpreters[executable] = append(interpreters[executable], id)
		}
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by tools/registrygen; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Linguist metadata: %s.\n", revision)
	fmt.Fprintln(&out, "// Copyright (c) 2017 GitHub, Inc. MIT license: LICENSE.linguist.")
	fmt.Fprintln(&out, "package languages\n\nconst (")
	for i := len(existing); i < len(names); i++ {
		if i == len(existing) {
			fmt.Fprintf(&out, "%s Language = Prolog + 1 + iota\n", symbols[i])
		} else {
			fmt.Fprintln(&out, symbols[i])
		}
	}
	fmt.Fprintln(&out, "LanguageCount\n)")
	fmt.Fprintln(&out, "var names = [...]string{")
	for _, name := range names {
		fmt.Fprintf(&out, "%q,\n", name)
	}
	fmt.Fprintln(&out, "}\nvar languageAliases = [...]nameEntry{")
	aliasKeys := sortedKeys(aliases)
	for _, alias := range aliasKeys {
		fmt.Fprintf(&out, "{%q, %d},\n", alias, aliases[alias])
	}
	fmt.Fprintln(&out, "}")
	writeTable(&out, "extensionRegistry", extensions)
	writeTable(&out, "filenameRegistry", filenames)
	fmt.Fprintf(&out, "var xmlLanguages = %s\n", setLiteral(xmlLanguages))
	fmt.Fprintln(&out, "var interpreterRules = [...]rule{")
	for _, key := range sortedKeys(interpreters) {
		fmt.Fprintf(&out, "{%q, %q, %s, declaredWeight, %q, \"\", \"\"},\n", "interpreter."+key, "interpreter "+key, setLiteral(interpreters[key]), "@"+key)
	}
	fmt.Fprintln(&out, "}")
	return format.Source(out.Bytes())
}

func catalog(entries map[string]metadata) ([]string, map[string]int, []string) {
	names := append([]string(nil), existing...)
	ids := make(map[string]int)
	for i, name := range names {
		ids[name] = i
	}
	keys := make([]string, 0, len(entries))
	for name := range entries {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	for _, name := range keys {
		if _, ok := equivalents[name]; ok {
			continue
		}
		if _, ok := ids[name]; !ok {
			ids[name] = len(names)
			names = append(names, name)
		}
	}
	for alias, name := range equivalents {
		ids[alias] = ids[name]
	}
	return names, ids, keys
}

func identifiers(names []string) ([]string, error) {
	symbols := make([]string, len(names))
	reserved := map[string]bool{"Unknown": true, "Language": true, "LanguageCount": true, "Set": true, "None": true, "Low": true, "Medium": true, "High": true, "Analysis": true, "Result": true, "Context": true, "Evidence": true, "Match": true, "Confidence": true}
	for i, name := range names {
		symbol := identifier(name)
		if i < len(existing) {
			reserved[symbol] = true
			continue
		}
		if reserved[symbol] {
			symbol += "Language"
		}
		if reserved[symbol] {
			return nil, fmt.Errorf("duplicate identifier: %s", symbol)
		}
		reserved[symbol] = true
		symbols[i] = symbol
	}
	return symbols, nil
}

func identifier(name string) string {
	name = strings.ReplaceAll(strings.ReplaceAll(name, "+", " Plus "), "#", " Sharp ")
	var b strings.Builder
	upper := true
	for _, r := range name {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if b.Len() == 0 && unicode.IsDigit(r) {
			b.WriteString("Language")
		}
		if upper {
			r = unicode.ToUpper(r)
		}
		b.WriteRune(r)
		upper = false
	}
	return b.String()
}

func sortedKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func setLiteral(ids []int) string {
	words := make(map[int]uint64)
	for _, id := range ids {
		words[id/wordBits] |= 1 << uint(id%wordBits)
	}
	indices := make([]int, 0, len(words))
	for i := range words {
		indices = append(indices, i)
	}
	sort.Ints(indices)
	parts := make([]string, 0, len(words))
	for _, i := range indices {
		parts = append(parts, fmt.Sprintf("%d: %s", i, strconv.FormatUint(words[i], 10)))
	}
	return "Set{words: [setWords]uint64{" + strings.Join(parts, ",") + "}}"
}

func writeTable(out *bytes.Buffer, name string, entries map[string][]int) {
	fmt.Fprintf(out, "var %s = [...]pathEntry{\n", name)
	for _, key := range sortedKeys(entries) {
		fmt.Fprintf(out, "{%q, %s},\n", key, setLiteral(entries[key]))
	}
	fmt.Fprintln(out, "}")
}
