// modelgen builds a bounded content classifier from Linguist samples.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/git-pkgs/languages"
	"github.com/git-pkgs/languages/internal/tokenize"
)

const (
	weightScale   = 256
	fileMode      = 0644
	directoryMode = 0755
	trainingBytes = 64 * 1024
)

type training struct {
	Counts   map[string]map[string]int
	Totals   map[string]int
	Files    map[string]int
	Total    int
	Manifest []sample
}

type sample struct {
	Path     string `json:"path"`
	Language string `json:"language"`
	SHA256   string `json:"prefix_sha256"`
	Bytes    int    `json:"bytes"`
}

func main() {
	corpus := flag.String("corpus", "", "Linguist samples directory")
	revision := flag.String("revision-file", "tools/registrygen/revision", "pinned Linguist revision")
	output := flag.String("out", "internal/classifier", "generated model directory")
	flag.Parse()
	if err := run(*corpus, *revision, *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(corpus, revisionFile, output string) error {
	revision, err := os.ReadFile(revisionFile)
	if err != nil {
		return err
	}
	commit := strings.TrimSpace(string(revision))
	if sha, err := hex.DecodeString(commit); err != nil || len(sha) != 20 {
		return fmt.Errorf("invalid Linguist commit SHA: %q", commit)
	}
	trained, err := train(corpus)
	if err != nil {
		return err
	}
	generated, err := trained.generate(commit)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(output, directoryMode); err != nil {
		return err
	}
	for _, name := range sortedKeys(generated) {
		if err := os.WriteFile(filepath.Join(output, name), generated[name], fileMode); err != nil {
			return err
		}
	}
	return nil
}

func train(corpus string) (*training, error) {
	if corpus == "" {
		return nil, fmt.Errorf("corpus is required")
	}
	t := &training{Counts: map[string]map[string]int{}, Totals: map[string]int{}, Files: map[string]int{}}
	err := filepath.WalkDir(corpus, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.Type().IsRegular() {
			return nil
		}
		relative, err := filepath.Rel(corpus, path)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		label, _, _ := strings.Cut(relative, "/")
		language := languages.Parse(label)
		if language == languages.Unknown {
			return fmt.Errorf("unmapped sample label %q", label)
		}
		data, err := readPrefix(path)
		if err != nil {
			return err
		}
		t.add(relative, language.String(), data)
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(t.Manifest) == 0 || t.Total == 0 {
		return nil, fmt.Errorf("corpus has no lexical tokens")
	}
	return t, nil
}

func readPrefix(path string) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	data, readErr := io.ReadAll(io.LimitReader(f, trainingBytes))
	closeErr := f.Close()
	if readErr != nil {
		return nil, readErr
	}
	return data, closeErr
}

func (t *training) add(path, language string, data []byte) {
	if t.Counts[language] == nil {
		t.Counts[language] = map[string]int{}
	}
	t.Files[language]++
	digest := sha256.Sum256(data)
	t.Manifest = append(t.Manifest, sample{path, language, hex.EncodeToString(digest[:]), len(data)})
	tokenize.Scan(data, func(token []byte) {
		t.Counts[language][string(token)]++
		t.Totals[language]++
		t.Total++
	})
}

type posting struct{ language, weight uint16 }

func (t *training) generate(revision string) (map[string][]byte, error) {
	names := sortedKeys(t.Counts)
	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by internal/modelgen; DO NOT EDIT.")
	fmt.Fprintf(&source, "// Linguist samples: %s.\npackage classifier\n", revision)
	fmt.Fprintln(&source, "var Names = [...]string{")
	for _, name := range names {
		fmt.Fprintf(&source, "%q,\n", name)
	}
	fmt.Fprintln(&source, "}\nvar priors = [...]int32{")
	index := map[string][]posting{}
	for id, name := range names {
		prior := math.Log(float64(t.Files[name]) / float64(len(t.Manifest)))
		fmt.Fprintf(&source, "%d,\n", int32(math.Round(prior*weightScale)))
		for token, count := range t.Counts[name] {
			weight := math.Log(float64(count) * float64(t.Total) / float64(t.Totals[name]))
			quantized := math.Round(weight * weightScale)
			if quantized < 0 || quantized > math.MaxInt32/trainingBytes {
				return nil, fmt.Errorf("token weight out of range: %q", token)
			}
			index[token] = append(index[token], posting{uint16(id), uint16(quantized)})
		}
	}
	fmt.Fprintln(&source, "}")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, err
	}
	directory, tokens, weights := encode(index)
	manifest, err := json.MarshalIndent(struct {
		Revision  string   `json:"revision"`
		ByteLimit int      `json:"byte_limit"`
		Tokens    int      `json:"tokens"`
		Samples   []sample `json:"samples"`
	}{revision, trainingBytes, t.Total, t.Manifest}, "", "  ")
	if err != nil {
		return nil, err
	}
	return map[string][]byte{"model_generated.go": formatted, "index.bin": directory, "tokens.bin": tokens, "weights.bin": weights, "training.json": append(manifest, '\n')}, nil
}

func encode(index map[string][]posting) (directory, tokens, weights []byte) {
	for _, token := range sortedKeys(index) {
		directory = binary.LittleEndian.AppendUint32(directory, uint32(len(tokens)))
		directory = binary.LittleEndian.AppendUint32(directory, uint32(len(token)))
		directory = binary.LittleEndian.AppendUint32(directory, uint32(len(weights)))
		directory = binary.LittleEndian.AppendUint32(directory, uint32(len(index[token])))
		tokens = append(tokens, token...)
		for _, p := range index[token] {
			weights = binary.LittleEndian.AppendUint16(weights, p.language)
			weights = binary.LittleEndian.AppendUint16(weights, p.weight)
		}
	}
	return directory, tokens, weights
}

func sortedKeys[T any](items map[string]T) []string {
	keys := make([]string, 0, len(items))
	for key := range items {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
